baseURL = 'https://wiktorkowalski.pl/'
languageCode = 'en-us'
title = 'Wiktor Kowalski - Backend Dev'
theme = 'hugo-resume'
PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Zielona Góra, PL"
email = "mail@wiktorkowalski.pl"
favicon = "website/favicon.ico"
firstName = "Wiktor"
lastName = "Kowalski"
profileImage = "website/img/TechChat.png"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[[params.handles]]
link = "https://www.linkedin.com/in/wiktor-kowalski/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/wiktorkowalski/"
name = "GitHub"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
